CREATE DATABASE feriavirtual;

USE feriavirtual;

CREATE TABLE VIDEOS
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR (100) NOT NULL,
    LINK VARCHAR(100) NOT NULL
)


CREATE TABLE INFORMACION
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR (100) NOT NULL
)

