CREATE DATABASE feriavirtual;

USE feriavirtual;

CREATE TABLE ESPECIALIDAD(
    IDESPECIALIDAD INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(200)
    );

CREATE TABLE VIDEOS
(
    IDVIDEO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    LINK VARCHAR(200) NOT NULL, 
    IDESPECIALIDAD INT,
	FOREIGN KEY(IDESPECIALIDAD) REFERENCES ESPECIALIDAD(IDESPECIALIDAD)
);

CREATE TABLE REUNION
(
    IDREUNION INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    LINK VARCHAR(200) NOT NULL, 
    IDESPECIALIDAD INT,
	FOREIGN KEY(IDESPECIALIDAD) REFERENCES ESPECIALIDAD(IDESPECIALIDAD)
);

CREATE TABLE INFORMACION
(
    IDINFORMACION INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR (200) NOT NULL,
	IDESPECIALIDAD INT,
	FOREIGN KEY(IDESPECIALIDAD) REFERENCES ESPECIALIDAD(IDESPECIALIDAD)
);

CREATE TABLE USUARIO
(
    IDUSUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	CEDULA VARCHAR (200) NOT NULL,
    NOMBRE VARCHAR (100) NOT NULL,
    APELLIDO1 VARCHAR (200) NOT NULL,
	APELLIDO2 VARCHAR (200) NOT NULL,
    CORREO VARCHAR (200) NOT NULL,
    CONTRASENA VARCHAR(200) NOT NULL
)
